ansible_network_os: eos

provider:
  host: "{{ ansible_host }}"
  username: arista
  password: arista
  authorize: yes
  transport: eapi
  validate_certs: no

domain_name: atd.local
dns_server: 192.168.0.4
ntp_server: time.google.com
timezone: America/Detroit

routerid: "172.16.0.{{ hostvars[inventory_hostname].deviceid }}"
