---

- name: Command output testing
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Test command output
      eos_command:
        commands: show ip ospf database
      register: ospfdatabase

    - name: Echo output of registered var
      debug:
        var: ospfdatabase
